services:
  backend:
    build: ./backend
    container_name: ecommerce_backend
    ports:
      - "5001:5001" # Maps Mac port 5001 to Container port 5001
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    ports:
      - "3000:3000" # Maps Mac port 3000 to Container port 3000
    command: npx vite --host 0.0.0.0 --port 3000 # Forces Vite to expose itself on port 3000
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allows Watchtower to control Docker
    command: --interval 60 # Checks Docker Hub every 60 seconds
    depends_on:
      - backend
      - frontend